app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))
    

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    author = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    password_hash = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pitch = db.relationship('Pitches', backref='author', lazy='dynamic')
    comments = db.relationship('Comments', backref='author', lazy='dynamic')

#to link tables what you add after backref matters
    @property
    def password(self):
        raise AttributeError('You cannnot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)

    def __repr__(self):
        return f'Author: {self.author}'

class Pitches(db.Model):
    __tablename__= 'pitches'
    id = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String(255))
    category = db.Column(db.String(255))
    pitch = db.Column(db.String(255))
    date = db.Column(db.DateTime(250), default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    comments = db.relationship('Comments', backref='title', lazy='dynamic')

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls,cate):
        pitch = Pitches.query.filter_by(category=cate).all()
        return pitch

    def __repr__(self):
        return f"Pitches {self.pitch}','{self.date}')"

class Comments(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.String(255))
    date_posted = db.Column(db.DateTime(250), default=datetime.utcnow)
    pitches_id = db.Column(db.Integer, db.ForeignKey("pitches.id"))
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comment(cls,id):
        comments = Comments.query.filter_by(pitches_id=id).all()
        return comments

    def __repr__(self):
        return f"Comments('{self.comment}', '{self.date_posted}')"

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required

class PitchForm(FlaskForm):
    title = StringField("Pitch Title")
    category = SelectField(u"Pitch Category",choices=[("Business", "Business"),("Health","Health"),("Dance","Dance"),("Eductional","Educational")])
    pitch = TextAreaField('Pitch')
    submit = SubmitField("Submit")

# add comment

class CommentForm(FlaskForm):
    
    comment = TextAreaField('Comment')
    submit = SubmitField('Post Comments')

# update profile

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()

def create_app(config_name):
    

    app = Flask(__name__)
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    # configure UploadSet
    configure_uploads(app,photos)

    # Initializing flask extensions
    Bootstrap(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

      # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # secret
    app.secret_key='SECRET_KEY'



    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views, errors

app/main/views.py
from flask_login import login_required,current_user
from ..models import Pitches, User, Comments
from . import main
from .. import db,photos
from .forms import PitchForm,CommentForm, UpdateProfile

# blueprint views
from flask import render_template,request,redirect,url_for,abort


# main route
@main.route('/')
def index():
    '''
    my index page
    return
    '''
    message= "Hello"
    title= 'Pitch'
    return render_template('index.html', message=message,title=title)

@main.route('/pitch/', methods = ['GET','POST'])
@login_required
def new_pitch():

    form = PitchForm()

    if form.validate_on_submit():
        category = form.category.data
        pitch= form.pitch.data
        title=form.title.data

        # Updated pitchinstance
        new_pitch = Pitches(title=title,category= category,pitch= pitch,user_id=current_user.id)

        title='New Pitch'

        new_pitch.save_pitch()

        return redirect(url_for('main.index'))

    return render_template('pitch.html',pitch_entry= form)

    # main route categories
@main.route('/categories/<cate>')
def category(cate):
    '''
    function to return the pitches by category
    '''
    category = Pitches.get_pitches(cate)
    # print(category)
    title = f'{cate}'
    return render_template('categories.html',title = title, category = category)

    # profile username
@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(author = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(author = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.author))

    return render_template('profile/update.html',form =form)

# updating profile picture 
@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(author = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

# login to make comment
@main.route('/comments/<id>')
@login_required
def comment(id):
    '''
    function to return the comments
    '''
    comm =Comments.get_comment(id)
    print(comm)
    title = 'comments'
    return render_template('comments.html',comment = comm,title = title)

# make new comment
@main.route('/new_comment/<int:pitches_id>', methods = ['GET', 'POST'])
@login_required
def new_comment(pitches_id):
    pitches = Pitches.query.filter_by(id = pitches_id).first()
    form = CommentForm()

    if form.validate_on_submit():
        comment = form.comment.data

        new_comment = Comments(comment=comment,user_id=current_user.id, pitches_id=pitches_id)


        new_comment.save_comment()


        return redirect(url_for('main.index'))
    title='New Pitch'
    return render_template('new_comment.html',title=title,comment_form = form,pitches_id=pitches_id)

app/templates/base.html
{% extends 'bootstrap/base.html'%} {% block navbar %} {% include 'navbar.html' %} {% endblock %}

<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>

    <meta charset="utf-8"> {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Choose </title>
    {% endif %}
</head>

<body>

    {% block content %} {% endblock %}

</body>

</html>

app/templates/categories.html
{% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.min.css')}}">

<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" crossorigin="anonymous" />
<style>
    body {
        background-color: darkgray;
    }
    
    .card {
        background-color: rgb(1, 11, 54);
        color: ghostwhite;
        margin-left: 5px;
        text-align: left;
        border-radius: 10px;
    }
    
    .button {
        padding-right: 5px;
        margin-left: 5px;
        text-align: center;
    }
</style>{% endblock %}

<br>
<br>
<br>
<br>

<body>
    {% block content %}
    <br>
    <br>
    <div class="container">
        <div class='card' style="width: 50rem;">
            &nbsp;&nbsp;&nbsp;
            <div class='card-body'>
                <h1 class=" card title ">Welcome to Pitch App</h1>
                &nbsp;&nbsp;&nbsp;
                <h3 class="card text ">You can create your own Pitch in any of our fields by clicking the link button below</h3>
                <button type="button " class="btn btn-success "><a href="../pitch/ ">Add Pitch</a></button><br>
            </div><br>
        </div>
        <br>
        <br>
        <br>
        <div class="card-columns ">
            {% for category in category[::-1] %}

            <div class="card bg-transparent border-success ">
                <div class="card-header bg-transparent border-success ">
                    {{category.title}}
                </div>
                <div class="card-body text ">
                    <blockquote class="blockquote mb-0 ">
                        <p>{{category.pitch}}</p><br>
                        <footer class="blockquote-footer bg-transparent border-success ">{{category.author}}
                            <br><cite title="Source Title ">Publish date: {{category.date.strftime('%Y-%m-%d')}}</cite>
                        </footer>
                    </blockquote>
                </div>
                <div class="card-footer bg-transparent border-success ">
                    <button type="button " class="btn btn-outline-success btn-sm "><a
              href="/new_comment/{{category.id}} ">Comment</a></button> <button type="button " class="btn btn-outline-success btn-sm "><a href="/comments/{{category.id}} ">View comments</a></button>
                </div>

                <p id="UpvoteCount "></p>

                <!-- upvote and downvote -->
                <div class="card-footer bg-transparent border-success ">
                    <button type="button " id="like " class="btn btn-info btn-sm ">

            <a class="text-decoration-none text-light " href=" ">Upvote <i class="fas fa-thumbs-up "></i></a></button>
                    <button type="button " class="btn btn-danger btn-sm "><a class="text-decoration-none text-light " href=" ">Downvote
              <i class="fas fa-thumbs-down "></i></a>
          </button>
                </div>
            </div><br><br> {% endfor %}

        </div>
        {% endblock %}
</body>

app/templates/comments.html
{% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block styles%} {{ super() }}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="static/css/style.css">
<style>
    body {
        background-color: rgb(139, 136, 136);
    }
</style>{% block content %}

<br>
<br>

<body>
    {% for comm in comment[::-1] %}
    <div class="container">
        <div class="card-groups">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{comm.author}}</h4>
                    <p class="card-text">{{comm.comment}}.</p>
                </div>
                <div class="card-footer bg-transparent border-success"><small class="text-muted">Publish date:{{comm.date_posted.strftime('%Y-%m-%d')}}</small></div>
            </div>
        </div>
    </div>

    {% endfor %} {% endblock %}
</body>

app/templates/fourOwfour.html
{% extends 'base.html'%} {% block content %}
<br>
<br>
<h1>SORRY! we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}

<!-- styles block -->
{% block styles%} {{ super() }}
<!-- <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.min.css')}}"> -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="static/css/style.css">


<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" crossorigin="anonymous" />
<style>
    body {
        background-color: darkgray;
    }
    
    h1 :hover {
        box-shadow: 0 0 10px rgba(45, 3, 85, 0.6), 0 0 20px rgba(45, 3, 85, 0.6), 0 0 40px rgba(45, 3, 85, 0.6);
    }
    /* .height {
        height: 250px;
    }
     */
    
    .col {
        background-color: dimgray;
        width: 500px;
        border-radius: 15px;
        color: indigo;
    }
    
    .card-text {
        font-size: large;
        color: black;
    }
    
    .card-header {
        font-size: xx-large;
    }
    
    .card-groups {
        background-color: dimgray;
        width: 500px;
        border-radius: 15px;
    }
    
    .card-groups:hover {
        box-shadow: 0 0 10px rgba(45, 3, 85, 0.6), 0 0 20px rgba(45, 3, 85, 0.6), 0 0 40px rgba(45, 3, 85, 0.6);
    }
    
    .col:hover {
        box-shadow: 0 0 10px rgba(45, 3, 85, 0.6), 0 0 20px rgba(45, 3, 85, 0.6), 0 0 40px rgba(45, 3, 85, 0.6);
    }
</style>{% endblock %} {% block content %}

<body style="color: rgb(61, 10, 95); text-align: center;">
    <div class="container">
        <h1>PITCH APP</h1>
        <br>
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="d-flex justify-content-center">
                    <div class="card-groups">
                        <div class="card border-info mb-5  height" style="max-width: 50rem;">
                            <div class="card-header">Business Pitch</div>
                            <div class="card-body text-info">
                                <p class="card-text">"...To be successful, you have to have your heart in your business, and your business in your heart..."</p>
                                <button type="button" class="btn btn-success"><a href="../pitch/">Add Pitch</a></button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <button type="button" class="btn btn-success"><a href="/categories/Business">View Pitch</a></button>
                            </div>
                            <br>
                        </div>
                    </div>
                    <br>
                    <br>

                    <!-- random pitches -->
                    <div class="col">
                        <div class="card border-info mb-5" style="max-width: 50rem;">
                            <div class="card-header">Health Pitches</div>
                            <div class="card-body text-info">
                                <p class="card-text">"...A fit body , a calm mind, a house full of love. These things cannot be bought, they are earned..."</p>
                                <button type="button" class="btn btn-success"><a href="../pitch/">Add Pitch</a></button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <button type="button" class="btn btn-success"><a href="/categories/Health">View Pitch</a></button>
                            </div>
                            <br>
                        </div>
                    </div>
                    <br>
                    <br>
                    <!-- random pitches -->
                    <div class="col">
                        <div class="card border-info mb-7" style="max-width: 50rem;">
                            <div class="card-header">Dance Pitches</div>
                            <div class="card-body text-info">
                                <p class="card-text">"...Hand in hand on the edge of sand, they danced by the light of moon..."</p>
                                <button type="button" class="btn btn-success"><a href="../pitch/">Add Pitch</a></button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <button type="button" class="btn btn-success"><a href="/categories/Dance">View Pitch</a></button>
                            </div>
                            <br>
                        </div>
                    </div>
                    <br>
                    <br>
                    <div class="col">
                        <div class="card border-info mb-7" style="max-width: 40rem;">
                            <div class="card-header">Educational Pitches</div>
                            <div class="card-body text-info">
                                <p class="card-text">"...Teachers open the door, but you must enter..."</p>
                                <button type="button" class="btn btn-success"><a href="../pitch/">Add Pitch</a></button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <button type="button" class="btn btn-success"><a href="/categories/Educational">View Pitch</a></button>
                            </div>
                            <br>
                        </div>
                    </div>
                    <br>
                    <br>
                </div>
            </div>
        </div>
    </div>

    {% endblock%}

</body>
</body>

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: rgb(13, 14, 14);">


    <div class="collapse navbar-collapse " id="navbarSupportedContent">
        <div class="navbar-nav">
            <strong><a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a></strong>&nbsp;&nbsp;&nbsp;
            <a class="nav-link" href="/categories/Business">Business</a>&nbsp;&nbsp;&nbsp;
            <a class="nav-link" href="/categories/Health">Health</a>&nbsp;&nbsp;&nbsp;
            <a class="nav-link" href="/categories/Dance">Dance</a>&nbsp;&nbsp;&nbsp;
            <a class="nav-link" href="/categories/Educational">Educational</a>&nbsp;&nbsp;&nbsp;

        </div>

        <!-- user section -->
        <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('main.profile',uname=current_user.author)}}">Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.logout')}}">Log out</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.login')}}">Sign in</a>
            </li>
            {%endif%}
        </ul>
    </div>
</nav>

app/templates/new_comment.html
{% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block content %}
<br>
<br>
<div class="container">
    <br>
    <br> {{ wtf.quick_form(comment_form) }}


</div>



{% endblock %}

app/templates/pitch.html
{% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block content %}
<br>
<br>
<style>
    body {
        background-color: grey;
    }
</style>

<body>


    <div class="container">
        <br>
        <br> {{ wtf.quick_form(pitch_entry) }}


    </div>
</body> {% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%} {% block styles%} {{ super() }}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="static/css/style.css">
<style>
    body {
        background-color: rgb(177, 174, 174);
    }
    
    .col-md-4 {
        background-color: rgb(0, 30, 130);
        color: lemonchiffon;
    }
    
    .col-md-8 {
        color: rgb(12, 12, 235);
    }
</style>{% endblock %} {% block content %} {% if user == current_user %} {% endif %}
<br>
<br>

<body>
    <div class="container">
        <div class="row">


            <!-- displaying  Username-->
            <div class="col-md-4">
                <h3>Author: {{user.author| capitalize}} </h3>
                <br>
                <hr>
                <a href="{{url_for('main.update_profile',uname=user.author)}}">Edit profile</a>

                <!--Displaying user bio-->
                {% if user.bio %}
                <br>
                <h4>{{user.bio}}</h4>
                {%else%}
                <br>
                <p> {{user.author| capitalize}} has no bio </p>
                {% endif %}
            </div>

            <!--Display profile photo-->
            <div class="col-md-8">
                {% if user.profile_pic_path %}

                <div class="card">
                    <img class="card" src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail" height=50%>
                </div>
                <div class="row">
                    {%else%}

                    <h3><strong>No profile picture</strong></h3>

                    {% endif %} {% if user == current_user %}
                    <form action="{{url_for('main.update_pic',uname=user.author)}}" method="post" enctype="multipart/form-data">
                        <br>
                        <input type="file" name="photo" class="form-control" required>
                        <br>
                        <input type="submit">

                    </form>
                    {% endif %}
                </div>
            </div>
        </div>

</body> {% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf %} {% block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}